"""Interactive or scripted creation of a Purrmox configuration file.

Interactive:      purrmox-setup --output /etc/purrmox/config.yaml
Non-interactive:  purrmox-setup --host 192.168.1.10 --token-id purrmox@pve!dash --secret-stdin \
                      --username admin --generate-password --output config.yaml

The API token secret is never accepted as a command-line argument, so it cannot leak through
the process list. Provide it interactively or on standard input (``--secret-stdin``).
"""
import argparse
import getpass
import os
import secrets
import sys

import yaml
from werkzeug.security import generate_password_hash


def build_config(host, token_id, token_secret, username, password_hash, listen_host="0.0.0.0",
                 port=8080, verify_ssl=False):
    """Return a complete configuration dictionary with sensible defaults."""
    return {
        "proxmox": {"host": host, "port": 8006, "token_id": token_id, "token_secret": token_secret,
                    "verify_ssl": verify_ssl, "timeout": 5},
        "listen": {"host": listen_host, "port": port},
        "auth": {"username": username, "password_hash": password_hash},
        "scan_ports": [22, 80, 443, 3000, 8000, 8080],
        "discord": {"enabled": False, "guild_id": "", "channel_id": "", "notify_start": True},
        "alerts": {"ram_percent": 90, "disk_percent": 90, "backup_max_age_hours": 48,
                   "cert_warn_days": 14, "cooldown_minutes": 360},
        "history": {"retention_days": 7},
        "poll_seconds": 30,
        "refresh_seconds": 15,
    }


def write_config(cfg, path):
    """Write the configuration with owner-only permissions (it contains a secret)."""
    header = "# Generated by purrmox-setup. See config.example.yaml for all available options.\n"
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(cfg, f, sort_keys=False)
    os.chmod(path, 0o600)


def main(argv=None):
    p = argparse.ArgumentParser(prog="purrmox-setup", description="Create a Purrmox configuration file.")
    p.add_argument("--output", default="config.yaml", help="where to write the configuration")
    p.add_argument("--host", help="Proxmox host name or IP address")
    p.add_argument("--token-id", help="API token ID, for example purrmox@pve!dash")
    p.add_argument("--secret-stdin", action="store_true", help="read the API token secret from standard input")
    p.add_argument("--username", default="admin", help="dashboard login name (default: admin)")
    p.add_argument("--generate-password", action="store_true",
                   help="generate a random dashboard password and print it once")
    p.add_argument("--listen-host", default="0.0.0.0")
    p.add_argument("--port", type=int, default=8080)
    p.add_argument("--force", action="store_true", help="overwrite an existing file")
    args = p.parse_args(argv)

    if os.path.exists(args.output) and not args.force:
        sys.exit(f"{args.output} already exists. Use --force to overwrite it.")

    host = args.host or input("Proxmox host or IP: ").strip()
    token_id = args.token_id or input("API token ID (user@realm!name): ").strip()
    if args.secret_stdin:
        token_secret = sys.stdin.readline().strip()
    else:
        token_secret = getpass.getpass("API token secret: ").strip()
    if not (host and token_id and token_secret):
        sys.exit("Host, token ID and token secret are all required.")

    if args.generate_password:
        password = secrets.token_urlsafe(12)
        print(f"Generated dashboard password for '{args.username}': {password}")
        print("Store it now; only its hash is saved.")
    else:
        password = getpass.getpass("Choose a dashboard password: ")
        if getpass.getpass("Repeat the password: ") != password:
            sys.exit("The passwords do not match.")
    cfg = build_config(host, token_id, token_secret, args.username, generate_password_hash(password),
                       listen_host=args.listen_host, port=args.port)
    write_config(cfg, args.output)
    print(f"Configuration written to {args.output}")


if __name__ == "__main__":
    main()
